CONFIG_BT_HCI_TI_CC3XXX=y

CONFIG_MBEDTLS=n

CONFIG_BT_HCI_ACL_FLOW_CONTROL=n
CONFIG_BT_PHY_UPDATE=n
CONFIG_BT_AUTO_PHY_UPDATE=n

CONFIG_NETWORKING=y
CONFIG_NET_L2_ETHERNET=y

# Below memory constraints are enforced by the Wi-Fi stack
CONFIG_HEAP_MEM_POOL_SIZE=122880
CONFIG_MAIN_STACK_SIZE=61440
CONFIG_NET_TX_STACK_SIZE=2048
CONFIG_NET_RX_STACK_SIZE=2048
CONFIG_DYNAMIC_THREAD_PREFER_POOL=y
CONFIG_DYNAMIC_THREAD_POOL_SIZE=4
CONFIG_DYNAMIC_THREAD_STACK_SIZE=8192
CONFIG_NET_PKT_RX_COUNT=10
CONFIG_NET_PKT_TX_COUNT=10
CONFIG_NET_BUF_RX_COUNT=20
CONFIG_NET_BUF_TX_COUNT=20
CONFIG_NET_MAX_CONTEXTS=10
